webtalk_init -webtalk_dir C:\\Users\\User\\Desktop\\VivadoWorkspace\\VivadoProjects\\mlp\\mlp.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-01-23 23:34:58" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pp5t4e44me6afdl5emuvubfq1j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.494 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1611437428770" -context "sdk\\\\bsp/1611437428770"
webtalk_add_data -client sdk -key hwid -value "1608291496399" -context "sdk\\\\bsp/1611437428770"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1611437428770"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1611437428770"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1611437428770"
webtalk_add_data -client sdk -key uid -value "1611437462100" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key hwid -value "1608291496399" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key bspid -value "1611437428770" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key projSize -value "588.90625" -context "sdk\\\\application/1611437462100"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key DebugCount -value "9" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1611441298508"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1611441298508"
webtalk_transmit -clientid 3836774266 -regid "" -xml C:\\Users\\User\\Desktop\\VivadoWorkspace\\VivadoProjects\\mlp\\mlp.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\User\\Desktop\\VivadoWorkspace\\VivadoProjects\\mlp\\mlp.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\User\\Desktop\\VivadoWorkspace\\VivadoProjects\\mlp\\mlp.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
