-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Wrapped_MLP is
generic (
    C_S_AXI_CONTROL_BUS_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
    s_axi_CONTROL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CONTROL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CONTROL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of Wrapped_MLP is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Wrapped_MLP,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.201400,HLS_SYN_LAT=547559,HLS_SYN_TPT=none,HLS_SYN_MEM=116,HLS_SYN_DSP=34,HLS_SYN_FF=5965,HLS_SYN_LUT=9693,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal INPUT_STREAM_data_V_0_vld_in : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_vld_out : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_ack_in : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_ack_out : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal INPUT_STREAM_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal INPUT_STREAM_data_V_0_sel_rd : STD_LOGIC := '0';
    signal INPUT_STREAM_data_V_0_sel_wr : STD_LOGIC := '0';
    signal INPUT_STREAM_data_V_0_sel : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_load_A : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_load_B : STD_LOGIC;
    signal INPUT_STREAM_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal INPUT_STREAM_data_V_0_state_cmp_full : STD_LOGIC;
    signal INPUT_STREAM_dest_V_0_vld_in : STD_LOGIC;
    signal INPUT_STREAM_dest_V_0_ack_out : STD_LOGIC;
    signal INPUT_STREAM_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal INPUT_STREAM_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_136_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal pixels_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixels_ce0 : STD_LOGIC;
    signal pixels_we0 : STD_LOGIC;
    signal pixels_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal pixels_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MLP_fu_113_ap_start : STD_LOGIC;
    signal grp_MLP_fu_113_ap_done : STD_LOGIC;
    signal grp_MLP_fu_113_ap_idle : STD_LOGIC;
    signal grp_MLP_fu_113_ap_ready : STD_LOGIC;
    signal grp_MLP_fu_113_pixels_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_MLP_fu_113_pixels_ce0 : STD_LOGIC;
    signal grp_MLP_fu_113_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal i_reg_102 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_MLP_fu_113_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call0 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_s_fu_142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return : STD_LOGIC_VECTOR (7 downto 0);

    component MLP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pixels_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixels_ce0 : OUT STD_LOGIC;
        pixels_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Wrapped_MLP_pixels IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Wrapped_MLP_CONTROL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    Wrapped_MLP_CONTROL_BUS_s_axi_U : component Wrapped_MLP_CONTROL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CONTROL_BUS_AWVALID,
        AWREADY => s_axi_CONTROL_BUS_AWREADY,
        AWADDR => s_axi_CONTROL_BUS_AWADDR,
        WVALID => s_axi_CONTROL_BUS_WVALID,
        WREADY => s_axi_CONTROL_BUS_WREADY,
        WDATA => s_axi_CONTROL_BUS_WDATA,
        WSTRB => s_axi_CONTROL_BUS_WSTRB,
        ARVALID => s_axi_CONTROL_BUS_ARVALID,
        ARREADY => s_axi_CONTROL_BUS_ARREADY,
        ARADDR => s_axi_CONTROL_BUS_ARADDR,
        RVALID => s_axi_CONTROL_BUS_RVALID,
        RREADY => s_axi_CONTROL_BUS_RREADY,
        RDATA => s_axi_CONTROL_BUS_RDATA,
        RRESP => s_axi_CONTROL_BUS_RRESP,
        BVALID => s_axi_CONTROL_BUS_BVALID,
        BREADY => s_axi_CONTROL_BUS_BREADY,
        BRESP => s_axi_CONTROL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => grp_MLP_fu_113_ap_return);

    pixels_U : component Wrapped_MLP_pixels
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => pixels_address0,
        ce0 => pixels_ce0,
        we0 => pixels_we0,
        d0 => pixels_d0,
        q0 => pixels_q0);

    grp_MLP_fu_113 : component MLP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_MLP_fu_113_ap_start,
        ap_done => grp_MLP_fu_113_ap_done,
        ap_idle => grp_MLP_fu_113_ap_idle,
        ap_ready => grp_MLP_fu_113_ap_ready,
        pixels_address0 => grp_MLP_fu_113_pixels_address0,
        pixels_ce0 => grp_MLP_fu_113_pixels_ce0,
        pixels_q0 => pixels_q0,
        ap_return => grp_MLP_fu_113_ap_return);





    INPUT_STREAM_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                INPUT_STREAM_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = INPUT_STREAM_data_V_0_ack_out) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_vld_out))) then 
                                        INPUT_STREAM_data_V_0_sel_rd <= not(INPUT_STREAM_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    INPUT_STREAM_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                INPUT_STREAM_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = INPUT_STREAM_data_V_0_ack_in) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_vld_in))) then 
                                        INPUT_STREAM_data_V_0_sel_wr <= not(INPUT_STREAM_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    INPUT_STREAM_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                INPUT_STREAM_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_in)) or ((ap_const_lv2_3 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_in) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_ack_out)))) then 
                    INPUT_STREAM_data_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_ack_out)) or ((ap_const_lv2_3 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_ack_out) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_vld_in)))) then 
                    INPUT_STREAM_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_in) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_ack_out))) and not(((ap_const_logic_0 = INPUT_STREAM_data_V_0_ack_out) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_vld_in))) and (ap_const_lv2_3 = INPUT_STREAM_data_V_0_state)) or ((ap_const_lv2_1 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_ack_out)) or ((ap_const_lv2_2 = INPUT_STREAM_data_V_0_state) and (ap_const_logic_1 = INPUT_STREAM_data_V_0_vld_in)))) then 
                    INPUT_STREAM_data_V_0_state <= ap_const_lv2_3;
                else 
                    INPUT_STREAM_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    INPUT_STREAM_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                INPUT_STREAM_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_dest_V_0_vld_in)) or ((ap_const_lv2_3 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_dest_V_0_vld_in) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_ack_out)))) then 
                    INPUT_STREAM_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_dest_V_0_ack_out)) or ((ap_const_lv2_3 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_0 = INPUT_STREAM_dest_V_0_ack_out) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_vld_in)))) then 
                    INPUT_STREAM_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = INPUT_STREAM_dest_V_0_vld_in) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_ack_out))) and not(((ap_const_logic_0 = INPUT_STREAM_dest_V_0_ack_out) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_vld_in))) and (ap_const_lv2_3 = INPUT_STREAM_dest_V_0_state)) or ((ap_const_lv2_1 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_ack_out)) or ((ap_const_lv2_2 = INPUT_STREAM_dest_V_0_state) and (ap_const_logic_1 = INPUT_STREAM_dest_V_0_vld_in)))) then 
                    INPUT_STREAM_dest_V_0_state <= ap_const_lv2_3;
                else 
                    INPUT_STREAM_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_MLP_fu_113_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_MLP_fu_113_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_MLP_fu_113_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MLP_fu_113_ap_ready = ap_const_logic_1)) then 
                    grp_MLP_fu_113_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_102 <= i_1_fu_136_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_102 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = INPUT_STREAM_data_V_0_load_A)) then
                INPUT_STREAM_data_V_0_payload_A <= INPUT_STREAM_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = INPUT_STREAM_data_V_0_load_B)) then
                INPUT_STREAM_data_V_0_payload_B <= INPUT_STREAM_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, INPUT_STREAM_data_V_0_vld_out, ap_CS_fsm_state2, exitcond_fu_130_p2, grp_MLP_fu_113_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_MLP_fu_113_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    INPUT_STREAM_TDATA_blk_n_assign_proc : process(INPUT_STREAM_data_V_0_state, ap_CS_fsm_state2, exitcond_fu_130_p2)
    begin
        if (((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            INPUT_STREAM_TDATA_blk_n <= INPUT_STREAM_data_V_0_state(0);
        else 
            INPUT_STREAM_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    INPUT_STREAM_TREADY <= INPUT_STREAM_dest_V_0_state(1);
    INPUT_STREAM_data_V_0_ack_in <= INPUT_STREAM_data_V_0_state(1);

    INPUT_STREAM_data_V_0_ack_out_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, ap_CS_fsm_state2, exitcond_fu_130_p2)
    begin
        if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            INPUT_STREAM_data_V_0_ack_out <= ap_const_logic_1;
        else 
            INPUT_STREAM_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    INPUT_STREAM_data_V_0_data_out_assign_proc : process(INPUT_STREAM_data_V_0_payload_A, INPUT_STREAM_data_V_0_payload_B, INPUT_STREAM_data_V_0_sel)
    begin
        if ((ap_const_logic_1 = INPUT_STREAM_data_V_0_sel)) then 
            INPUT_STREAM_data_V_0_data_out <= INPUT_STREAM_data_V_0_payload_B;
        else 
            INPUT_STREAM_data_V_0_data_out <= INPUT_STREAM_data_V_0_payload_A;
        end if; 
    end process;

    INPUT_STREAM_data_V_0_load_A <= (not(INPUT_STREAM_data_V_0_sel_wr) and INPUT_STREAM_data_V_0_state_cmp_full);
    INPUT_STREAM_data_V_0_load_B <= (INPUT_STREAM_data_V_0_state_cmp_full and INPUT_STREAM_data_V_0_sel_wr);
    INPUT_STREAM_data_V_0_sel <= INPUT_STREAM_data_V_0_sel_rd;
    INPUT_STREAM_data_V_0_state_cmp_full <= '0' when (INPUT_STREAM_data_V_0_state = ap_const_lv2_1) else '1';
    INPUT_STREAM_data_V_0_vld_in <= INPUT_STREAM_TVALID;
    INPUT_STREAM_data_V_0_vld_out <= INPUT_STREAM_data_V_0_state(0);

    INPUT_STREAM_dest_V_0_ack_out_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, ap_CS_fsm_state2, exitcond_fu_130_p2)
    begin
        if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            INPUT_STREAM_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            INPUT_STREAM_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    INPUT_STREAM_dest_V_0_vld_in <= INPUT_STREAM_TVALID;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state2_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, exitcond_fu_130_p2)
    begin
                ap_block_state2 <= ((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out));
    end process;


    ap_block_state2_ignore_call0_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, exitcond_fu_130_p2)
    begin
                ap_block_state2_ignore_call0 <= ((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out));
    end process;


    ap_done_assign_proc : process(grp_MLP_fu_113_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_MLP_fu_113_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_MLP_fu_113_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_MLP_fu_113_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    exitcond_fu_130_p2 <= "1" when (i_reg_102 = ap_const_lv10_310) else "0";
    grp_MLP_fu_113_ap_start <= grp_MLP_fu_113_ap_start_reg;
    i_1_fu_136_p2 <= std_logic_vector(unsigned(i_reg_102) + unsigned(ap_const_lv10_1));

    pixels_address0_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_130_p2, grp_MLP_fu_113_pixels_address0, ap_CS_fsm_state3, tmp_s_fu_142_p1)
    begin
        if (((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            pixels_address0 <= tmp_s_fu_142_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            pixels_address0 <= grp_MLP_fu_113_pixels_address0;
        else 
            pixels_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    pixels_ce0_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, ap_CS_fsm_state2, exitcond_fu_130_p2, grp_MLP_fu_113_pixels_ce0, ap_CS_fsm_state3)
    begin
        if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            pixels_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            pixels_ce0 <= grp_MLP_fu_113_pixels_ce0;
        else 
            pixels_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pixels_d0 <= INPUT_STREAM_data_V_0_data_out;

    pixels_we0_assign_proc : process(INPUT_STREAM_data_V_0_vld_out, ap_CS_fsm_state2, exitcond_fu_130_p2)
    begin
        if ((not(((exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_0 = INPUT_STREAM_data_V_0_vld_out))) and (exitcond_fu_130_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            pixels_we0 <= ap_const_logic_1;
        else 
            pixels_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_102),64));
end behav;
